run:
  timeout: 5m
  tests: true
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - revive
linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "disableStutteringCheck"]
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0